export const EventState =  [ "new", "upcoming", "live" ]
export const EventType = [
    'american_football_match',
    'american_football_outright',
    'baseball_match',
    'baseball_outright',
    'basketball_esports_match',
    'basketball_match',
    'boxing_match',
    'call_of_duty_match',
    'cricket_match',
    'cricket_outright',
    'csgo_match',
    'current_affairs',
    'cycling',
    'darts_match',
    'darts_outright',
    'dota_2_match',
    'football_esports_match',
    'football_match',
    'football_outright',
    'golf_match',
    'golf_outright',
    'greyhound_racing_race',
    'handball_match',
    'horse_racing_race',
    'ice_hockey_match',
    'league_of_legends_match',
    'mma_match',
    'motorsports_race',
    'motorsports_outright',
    'politics',
    'politics_outright',
    'rowing',
    'rugby_league_match',
    'rugby_league_outright',
    'rugby_union_match',
    'rugby_union_outright',
    'snooker_match',
    'snooker_outright',
    'table_tennis_match',
    'table_tennis_outright',
    'tennis_match',
    'tennis_outright',
    'volleyball_match',
    'generic',
    'top_level_event',
    'tv_entertainmen',
    "map",
];

export const EventColumn = [{
    title: 'bettable',
    dataIndex: 'bettable',
    key: 'bettable',
  }, {
    title: 'chart_time_period',
    dataIndex: 'chart_time_period',
    key: 'chart_time_period',
  }, {
    title: 'created',
    dataIndex: 'created',
    key: 'created',
  }, {
    title: 'description',
    dataIndex: 'description',
    key: 'description',
  }, {
    title: 'display_order',
    dataIndex: 'display_order',
    key: 'display_order',
  }, {
    title: 'end_date',
    dataIndex: 'end_date',
    key: 'end_date',
  }, {
    title: 'full_slug',
    dataIndex: 'full_slug',
    key: 'full_slug',
  }, {
    title: 'inplay_enabled',
    dataIndex: 'inplay_enabled',
    key: 'inplay_enabled',
  }, {
    title: 'modified',
    dataIndex: 'modified',
    key: 'modified',
  }, {
    title: 'name',
    dataIndex: 'name',
    key: 'name',
  }, {
    title: 'seo_description',
    dataIndex: 'seo_description',
    key: 'seo_description',
  }, {
    title: 'short_name',
    dataIndex: 'short_name',
    key: 'short_name',
  }, {
    title: 'slug',
    dataIndex: 'slug',
    key: 'slug',
  }, {
    title: 'special_rules',
    dataIndex: 'special_rules',
    key: 'special_rules',
  }, {
    title: 'start_date',
    dataIndex: 'start_date',
    key: 'start_date',
  }, {
    title: 'start_datetime',
    dataIndex: 'start_datetime',
    key: 'start_datetime',
  }, {
    title: 'state',
    dataIndex: 'state',
    key: 'state',
  }, {
    title: 'type',
    dataIndex: 'type',
    key: 'type',
  }];